### ISSUE TITLE
"Error retrieving list of datasources" but not aborting chef run

### ISSUE THREAD

**Issue by gretel** [sous-chefs/grafana#110]
while i don't get the error message itself the chef-run should abort and not continue.
currently, a value of `nil` is passed and therefore the call of `.each` can only fail.

```
* grafana_datasource[graphite.in] action create[2015-11-18T16:37:04+00:00] ERROR: Error retrieving list of datasources.


================================================================================
 Error executing action `create` on resource 'grafana_datasource[graphite.in]'
 ================================================================================

 NoMethodError
 -------------
 undefined method `each' for nil:NilClass


 ---------------
 /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:27:in `block in class_from_file'

 Resource Declaration:
 ---------------------
 # In /tmp/kitchen/cache/cookbooks/xpl_grafana/recipes/_grafana.rb

  32: grafana_datasource 'graphite.in' do
  33:   datasource(
  34:     type: 'graphite',
  35:     url: 'http://graphite.in',
  36:     access: 'proxy'
  37:   )
  38: end
  39:

 Compiled Resource:
 ------------------
 # Declared in /tmp/kitchen/cache/cookbooks/xpl_grafana/recipes/_grafana.rb:32:in `from_file'
```

**Comment by iksaif** [comment]
Same issue here
