### ISSUE TITLE
undefined method `datasource' for LWRP resource grafana_datasource from cookbook grafana

### ISSUE THREAD

**Issue by cyberflow** [sous-chefs/grafana#123]
Hello,

I'll try to use resource grafana_datasource. I created my own recipe like this:

```
include_recipe 'grafana::default'

grafana_datasource 'statsd' do
  datasource(
    type: 'influxdb_09',
    url: 'http://127.0.0.1:8086',
    access: 'proxy',
    database: 'statsd',
    user: 'statsd',
    password: 'statsd',
    isdefault: false
  )
  action :create
end
```

In metadata.rb of my recipe i have:

```
depends 'grafana'
```

After run:

```
================================================================================
         Recipe Compile Error in /tmp/kitchen/cache/cookbooks/wz-grafana/recipes/default.rb
         ================================================================================

         NoMethodError
         -------------
         undefined method `datasource' for LWRP resource grafana_datasource from cookbook grafana

         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/wz-grafana/recipes/default.rb:23:in `block in from_file'
           /tmp/kitchen/cache/cookbooks/wz-grafana/recipes/default.rb:22:in `from_file'

         Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/wz-grafana/recipes/default.rb:

          16:  # See the License for the specific language governing permissions and
          17:  # limitations under the License.
          18:  #
          19:
          20:  include_recipe 'grafana::default'
          21:
          22:  grafana_datasource 'statsd' do
          23>>   datasource(
          24:      type: 'influxdb_09',
          25:      url: 'http://127.0.0.1:8086',
          26:      access: 'proxy',
          27:      database: 'statsd',
          28:      user: 'statsd',
          29:      password: 'statsd',
          30:      isdefault: false
          31:    )
          32:    action :create


         Running handlers:
       [2016-01-22T10:13:52+00:00] ERROR: Running exception handlers
         Running handlers complete
       [2016-01-22T10:13:52+00:00] ERROR: Exception handlers complete
         Chef Client failed. 3 resources updated in 03 seconds
       [2016-01-22T10:13:52+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-01-22T10:13:52+00:00] ERROR: undefined method `datasource' for LWRP resource grafana_datasource from cookbook grafana
       [2016-01-22T10:13:52+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by JonathanTron** [comment]
Hi, what version of the cookbook are you using?

**Comment by cyberflow** [comment]
Hi @JonathanTron. I use 2.1.3 - latest from supermarket

**Comment by JonathanTron** [comment]
That's what I thought, we've changed the usage in `master`.

Please refer to README for the 2.1.3 version for correct syntax in the _released_ cookbook: https://github.com/JonathanTron/chef-grafana/tree/v2.1.3

**Comment by cyberflow** [comment]
Thanks. It's working.
