### ISSUE TITLE
NoMethodError: undefined method `organization_name' for Custom resource grafana_organization from cookbook grafana

### ISSUE THREAD

**Issue by ton31337** [sous-chefs/grafana#156]
This happens with chef-client 12.16.42
```
>>>> Caused by NoMethodError: undefined method `organization_name' for Custom resource grafana_organization from cookbook grafana
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:1366:in `method_missing'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:519:in `block in state_for_resource_reporter'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:517:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:517:in `state_for_resource_reporter'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/data_collector/resource_report.rb:71:in `to_hash'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/data_collector.rb:389:in `add_resource_report'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/data_collector.rb:226:in `resource_completed'
```
Is this really needed to be back reported to Chef server? https://github.com/JonathanTron/chef-grafana/blob/master/resources/organization.rb#L4

**Comment by ton31337** [comment]
ping @JonathanTron

**Comment by howdoicomputer** [comment]
Ah, yeah, same problem here.
