### ISSUE TITLE
Node attributes are read-only when you do not specify which precedence level to set

### ISSUE THREAD

**Issue by yeiniel** [sous-chefs/grafana#168]
I start using this cookbook and i found this problem when trying to set grafana['ini']['paths']['plugins']. Researching i found that on Chef v > 11 there is a deprecated API that cause this issue. The complete error is:

```
Chef::Exceptions::ImmutableAttributeModification
192.168.1.219 ------------------------------------------------
192.168.1.219 Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
192.168.1.219
192.168.1.219 Cookbook Trace:
192.168.1.219 ---------------
192.168.1.219   /var/chef/cache/cookbooks/grafana/recipes/default.rb:63:in `from_file'
192.168.1.219   /var/chef/cache/cookbooks/sorba_dashboard/recipes/application.rb:7:in `from_file'
192.168.1.219
192.168.1.219 Relevant File Content:
192.168.1.219 ----------------------
192.168.1.219 /var/chef/cache/cookbooks/grafana/recipes/default.rb:
192.168.1.219
192.168.1.219  56:    group 'root'
192.168.1.219  57:    mode '0644'
192.168.1.219  58:    notifies :restart, 'service[grafana-server]', :delayed
192.168.1.219  59:  end
192.168.1.219  60:
192.168.1.219  61:  ini = node['grafana']['ini'].dup
192.168.1.219  62:  ini['paths'] ||= {}
192.168.1.219  63>> ini['paths']['data'] = node['grafana']['data_dir']
192.168.1.219  64:  ini['paths']['logs'] = node['grafana']['log_dir']
192.168.1.219  65:
192.168.1.219  66:  template "#{node['grafana']['conf_dir']}/grafana.ini" do
192.168.1.219  67:    source 'grafana.ini.erb'
192.168.1.219  68:    variables ini: ini
192.168.1.219  69:    owner 'root'
192.168.1.219  70:    group 'root'
192.168.1.219  71:    mode '0644'
192.168.1.219  72:    notifies :restart, 'service[grafana-server]', :immediately
192.168.1.219
192.168.1.219 System Info:
192.168.1.219 ------------
192.168.1.219 chef_version=12.21.3
192.168.1.219 platform=ubuntu
192.168.1.219 platform_version=16.04
192.168.1.219 ruby=ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
192.168.1.219 program_name=chef-client worker: ppid=26833;start=11:42:03;
192.168.1.219 executable=/opt/chef/bin/chef-client
```

**Comment by scopenco** [comment]
`ini` has been moved to `attributes/default.rb`. Fixed in v2.2.0
