### ISSUE TITLE
Error creating dashboards

### ISSUE THREAD

**Issue by Lechucico** [sous-chefs/grafana#173]
The following sentence doesn't create a new dashboard: `grafana_dashboard 'customers'`

And this has an error on compile time: 

```
grafana_dashboard 'Customers' do
  dashboard(
    source: 'customers',
    overwrite: false
  )
end
```

 ```
================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/living-grafana/recipes/default.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `dashboard' for Custom resource grafana_dashboard from cookbook grafana

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/living-grafana/recipes/default.rb:47:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/living-grafana/recipes/default.rb:46:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/living-grafana/recipes/default.rb:

        40:      isdefault: true
        41:    )
        42:    action :create
        43:    retries 5
        44:  end
        45:  #grafana_dashboard 'customers'
        46:  grafana_dashboard 'Customers' do
        47>>   dashboard(
        48:      source: 'customers',
        49:      overwrite: false
        50:    )
        51:  end
        52:
        53:  directory '/etc/living/grafana' do
        54:    owner 'root'
        55:    group 'root'
        56:    mode '0755'

       System Info:
       ------------
       chef_version=13.4.24
       platform=centos
       platform_version=7.3.1611
       ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
       program_name=chef-client worker: ppid=4412;start=08:24:18;
       executable=/opt/chef/bin/chef-client


       Running handlers:
       [2017-09-29T08:24:20+00:00] ERROR: Running exception handlers
       [2017-09-29T08:24:20+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-09-29T08:24:20+00:00] ERROR: Exception handlers complete
       [2017-09-29T08:24:20+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 02 seconds
       [2017-09-29T08:24:20+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-09-29T08:24:20+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-09-29T08:24:20+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-09-29T08:24:20+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-09-29T08:24:20+00:00] ERROR: undefined method `dashboard' for Custom resource grafana_dashboard from cookbook grafana
       [2017-09-29T08:24:20+00:00] ERROR: undefined method `dashboard' for Custom resource grafana_dashboard from cookbook grafana
       [2017-09-29T08:24:20+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-09-29T08:24:20+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-centos-73>.  Please see .kitchen/logs/default-centos-73.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by xorima** [comment]
Hi,
v4.0.0 has been released,

could you please re-open this issue if it is still having problems?

Thanks
