### ISSUE TITLE
Error when node['grafana']['webserver'] = 'nginx'

### ISSUE THREAD

**Issue by Lechucico** [sous-chefs/grafana#175]
When I try to activate nginx this error appears:

```
================================================================================
         Recipe Compile Error in /tmp/kitchen/cache/cookbooks/living-grafana/recipes/default.rb
         ================================================================================

         Chef::Exceptions::ValidationFailed
         ----------------------------------
         Property template must be one of: String, Array!  You passed false.

         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/grafana/recipes/_nginx.rb:39:in `block in from_file'
           /tmp/kitchen/cache/cookbooks/grafana/recipes/_nginx.rb:38:in `from_file'
           /tmp/kitchen/cache/cookbooks/grafana/recipes/default.rb:21:in `from_file'
           /tmp/kitchen/cache/cookbooks/living-grafana/recipes/default.rb:58:in `from_file'

         Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/grafana/recipes/_nginx.rb:

          32:      server_aliases: node['grafana']['webserver_aliases'],
          33:      listen_address: node['grafana']['webserver_listen'],
          34:      listen_port: node['grafana']['webserver_port']
          35:    )
          36:  end
          37:
          38:  nginx_site 'grafana' do
          39>>   template false
          40:  end
          41:

         System Info:
         ------------
         chef_version=13.5.3
         platform=centos
         platform_version=7.3.1611
         ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
         program_name=chef-client worker: ppid=5653;start=10:19:21;
         executable=/opt/chef/bin/chef-client


         Running handlers:
       [2017-10-16T10:19:27+00:00] ERROR: Running exception handlers
       [2017-10-16T10:19:27+00:00] ERROR: Running exception handlers
         Running handlers complete
       [2017-10-16T10:19:27+00:00] ERROR: Exception handlers complete
       [2017-10-16T10:19:27+00:00] ERROR: Exception handlers complete
         Chef Client failed. 2 resources updated in 05 seconds
       [2017-10-16T10:19:27+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-10-16T10:19:27+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-10-16T10:19:27+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-10-16T10:19:27+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-10-16T10:19:27+00:00] ERROR: Property template must be one of: String, Array!  You passed false.
       [2017-10-16T10:19:27+00:00] ERROR: Property template must be one of: String, Array!  You passed false.
       [2017-10-16T10:19:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-10-16T10:19:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

If I just use `node['grafana']['webserver'] = ''` grafana works perfectly, but I need nginx.

**Comment by gumdelli** [comment]
https://github.com/JonathanTron/chef-grafana/blob/master/recipes/_nginx.rb#L39
Try updating the above line to 
```
nginx_site 'grafana' do
  action :enable
end
```

**Comment by Lechucico** [comment]
I can't update that line because I don't have that recipe. I'm using my own recipe, and this is how it is:

```
node.default['grafana']['version'] = '4.5.2'
node.default['grafana']['file']['checksum']['rpm'] = '2185db058a25ff6608e581b18e92e950395eedd367ce3e0d5df4b8ee8a1cb35f'
node.default['grafana']['file']['url'] = 'https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana'
node.default['grafana']['webserver'] = 'nginx'

include_recipe 'influxdb::default'
influxdb_database 'living' do
  action :create
end

yum_package 'urw-fonts' do
	action :install
end

include_recipe 'grafana::default'
grafana_datasource 'InfluxDB' do
  source(
    type: 'influxdb',
    url: 'http://localhost:8086',
    access: 'proxy',
    database: 'living',
    isdefault: true
  )
  action :create
  retries 5
end

grafana_dashboard 'customers'
```

If grafana webserver is nxing the error shown appears, if not it installs correctly

**Comment by gumdelli** [comment]
Clone this repository, change the above mentioned line, upload it to your `chef-server` and your cookbook should pick up the updated `grafana` dependency that you have on your chef-server

**Comment by gumdelli** [comment]
This PR should fix this issue: https://github.com/sous-chefs/chef-grafana/pull/176
