### ISSUE TITLE
Undefined method when trying to update organization

### ISSUE THREAD

**Issue by Lechucico** [sous-chefs/grafana#177]
```
==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/living-grafana/recipes/default.rb
==> default: ================================================================================
==> default:
==> default: NoMethodError
==> default: -------------
==> default: undefined method `organization' for Custom resource grafana_organization from cookbook grafana
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/living-grafana/recipes/default.rb:56:in `block in from_file'
==> default:   /var/chef/cache/cookbooks/living-grafana/recipes/default.rb:55:in `from_file'
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/living-grafana/recipes/default.rb:
==> default:
==> default:  49:      isdefault: true
==> default:  50:    )
==> default:  51:    action :create
==> default:  52:    retries 5
==> default:  53:  end
==> default:  54:
==> default:  55:  grafana_organization 'Main Org.' do
==> default:  56>>   organization(
==> default:  57:      name: 'Main Org 2.'
==> default:  58:    )
==> default:  59:    action :update
==> default:  60:  end
==> default:  61:
==> default:  62:  grafana_organization 'Marketing'
==> default:  63:
==> default:  64:  grafana_user 'lechucico' do
==> default:  65:    user(
==> default:
==> default: Platform:
==> default: ---------
==> default: x86_64-linux
```

**Comment by xorima** [comment]
Hi,
v4.0.0 has been released,

could you please re-open this issue if it is still having problems?

Thanks
