### ISSUE TITLE
Undefined method when trying to create new user

### ISSUE THREAD

**Issue by Lechucico** [sous-chefs/grafana#178]
```
==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/living-grafana/recipes/default.rb
==> default: ================================================================================
==> default:
==> default: Chef::Exceptions::ValidationFailed
==> default: ----------------------------------
==> default: Option user must be a kind of [String]!  You passed {:name=>"lechucico", :email=>"lechucico@example.com", :password=>"lechu", :isAdmin=>true, :organizations=>[{:name=>"Administration", :role=>"Admin"}, {:name=>"Marketing", :role=>"Admin"}]}.
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/living-grafana/recipes/default.rb:51:in `block in from_file'
==> default:   /var/chef/cache/cookbooks/living-grafana/recipes/default.rb:50:in `from_file'
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/living-grafana/recipes/default.rb:
==> default:
==> default:  44:  #  action :update
==> default:  45:  #end
==> default:  46:
==> default:  47:  grafana_organization 'Administration'
==> default:  48:  grafana_organization 'Marketing'
==> default:  49:
==> default:  50:  grafana_user 'lechucico' do
==> default:  51>>   user(
==> default:  52:      name: 'lechucico',
==> default:  53:      email: 'lechucico@example.com',
==> default:  54:      password: 'lechu',
==> default:  55:      isAdmin: true,
==> default:  56:      organizations: [
==> default:  57:        { name: 'Administration', role: 'Admin' },
==> default:  58:        { name: 'Marketing', role: 'Admin' }
==> default:  59:      ]
==> default:  60:    )
==> default:
==> default: Platform:
==> default: ---------
==> default: x86_64-linux
```

**Comment by xorima** [comment]
Hi,
v4.0.0 has been released,

could you please re-open this issue if it is still having problems?

Thanks
