### ISSUE TITLE
Error executing action `install` on resource 'grafana_config_paths[grafana]'

### ISSUE THREAD

**Issue by mcaulifn** [sous-chefs/grafana#228]
### Cookbook version
4.0.0

### Chef-client version
14.11.21

### Platform Details
Centos 7

### Scenario:
Set provisioning dir

### Steps to Reproduce:
```ruby
grafana_config_paths 'grafana' do
  provisioning '/etc/grafana/provisioning'
end
```
`kitchen converge`

### Expected Result:
set provisioning dir

### Actual Result:
```
 ================================================================================
           Error executing action `install` on resource 'grafana_config_paths[grafana]'
           ================================================================================
           
           NoMethodError
           -------------
           undefined method `[]' for nil:NilClass
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/grafana/resources/config_paths.rb:39:in `block (3 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/grafana/resources/config_paths.rb:34:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/grafana/resources/config_paths.rb:33:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/ntg-perf/recipes/default.rb
           
            22: grafana_config_paths 'grafana' do
            23:   provisioning '/etc/grafana/provisioning'
            24: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/ntg-perf/recipes/default.rb:22:in `from_file'
           
           grafana_config_paths("grafana") do
             action [:install]
             default_guard_interpreter :default
             declared_type :grafana_config_paths
             cookbook_name "ntg-perf"
             recipe_name "default"
             provisioning "/etc/grafana/provisioning"
             config_file "/etc/grafana/grafana.ini"
             instance_name "grafana"
           end

**Comment by xorima** [comment]
Did you call grafana_config first as this is a requirement, see: https://github.com/sous-chefs/grafana#configuration-resource-features

so ideally your recipe would look like:

```
grafana_config 'grafana'

grafana_config_paths 'grafana' do
  provisioning '/etc/grafana/provisioning'
end
```

**Comment by mcaulifn** [comment]
that did it

thank you!
