### ISSUE TITLE
Grafana installation fails when platform is amazon

### ISSUE THREAD

**Issue by justinas-b** [sous-chefs/grafana#229]
Grafana installation fails when platform is set to 'amazon', as it does not populate repository address:
```
    * yum_package[grafana] action install
      
================================================================================
      Error executing action `install` on resource 'yum_package[grafana]'
      ================================================================================
      
      RuntimeError
      ------------
      yum-helper.py had stderr/stdout output:
      
      Traceback (most recent call last):
        File "/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider/package/yum/yum_helper.py", line 205, in <module>
          query(command)
        File "/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/provider/package/yum/yum_helper.py", line 121, in query
          obj = base.pkgSack
        File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1074, in <lambda>
          pkgSack = property(fget=lambda self: self._getSacks(),
        File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 778, in _getSacks
          self.repos.populateSack(which=repos)
        File "/usr/lib/python2.7/site-packages/yum/repos.py", line 347, in populateSack
          self.doSetup()
        File "/usr/lib/python2.7/site-packages/yum/repos.py", line 157, in doSetup
          self.retrieveAllMD()
        File "/usr/lib/python2.7/site-packages/yum/repos.py", line 88, in retrieveAllMD
          dl = repo._async and repo._commonLoadRepoXML(repo)
        File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1525, in _commonLoadRepoXML
          result = self._getFileRepoXML(local, text)
        File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1302, in _getFileRepoXML
          size=102400) # setting max size as 100K
        File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 1068, in _getFile
          result = self.grab.urlgrab(misc.to_utf8(remote), local,
        File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 737, in <lambda>
          grab = property(lambda self: self._getgrab())
        File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 732, in _getgrab
          self._setupGrab()
        File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 662, in _setupGrab
          urls = self.urls
        File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 915, in <lambda>
          urls = property(fget=lambda self: self._geturls(),
        File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 912, in _geturls
          self._baseurlSetup()
        File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 878, in _baseurlSetup
          self.check()
        File "/usr/lib/python2.7/site-packages/yum/yumRepo.py", line 589, in check
          'Cannot find a valid baseurl for repo: %s' % self.ui_id
      yum.Errors.RepoError: Cannot find a valid baseurl for repo: grafana
      Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
      
      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/grafana/resources/install.rb
      
       65:     package 'grafana' do
       66:       version new_resource.version if new_resource.version
       67:     end
       68: 
```

Below code should be replaced with:
https://github.com/sous-chefs/grafana/blob/5f6b72826de204fe94d955f2ba907e14d1642ef3/resources/install.rb#L33

```
  when 'rhel', 'amazon'
```

**Comment by xorima** [comment]
Can you issue a quick pr for this with a patch version bump and I should be able to get this out quickly

**Comment by xorima** [comment]
@justinas-b Released to supermarket, thanks for this
