### ISSUE TITLE
grafana_config_security resource failing

### ISSUE THREAD

**Issue by justinas-b** [sous-chefs/grafana#233]
### Cookbook version
4.0.0

### Chef-client version
Chef 14.11.21

### Platform Details
Amazon Linux 2

### Scenario:
When executing below resource
```
grafana_config_security 'grafana_security_configuration' do
  admin_user       grafana_secrets['admin_username']
  admin_password   grafana_secrets['admin_password']
  secret_key       grafana_secrets['admin_secret']
  disable_gravatar false
end
```

Chef throughs error message:

```
  * grafana_config_security[grafana_security_configuration] action install
    
    ================================================================================
    Error executing action `install` on resource 'grafana_config_security[grafana_security_configuration]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/grafana/resources/config_security.rb:43:in `block (3 levels) in class_from_file'
    /var/chef/cache/cookbooks/grafana/resources/config_security.rb:38:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/grafana/resources/config_security.rb:37:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/grafana_wrapper/recipes/configure2.rb
    
      3: grafana_config_security 'grafana_security_configuration' do
      4:   admin_user       grafana_secrets['admin_username']
      5:   admin_password   grafana_secrets['admin_password']
      6:   secret_key       grafana_secrets['admin_secret']
      7:   disable_gravatar false
      8: end
      9: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/grafana_wrapper/recipes/configure2.rb:3:in `from_file'
```

### Steps to Reproduce:
Not applicable

### Expected Result:
Grafana security config resource should succeed

### Actual Result:
```
   NoMethodError
    -------------
    undefined method `[]' for nil:NilClass
```

**Comment by xorima** [comment]
Thanks for raising this,
Did you call grafana_config first as this is a requirement, see: https://github.com/sous-chefs/grafana#configuration-resource-features

so ideally your recipe would look like:
```
grafana_config 'grafana'

grafana_config_security 'grafana_security_configuration' do
  admin_user       grafana_secrets['admin_username']
  admin_password   grafana_secrets['admin_password']
  secret_key       grafana_secrets['admin_secret']
  disable_gravatar false
end
```

**Comment by justinas-b** [comment]
oh, it seems i have misinterpreted documentation. It works fine once i call the base resource in very beginning

**Comment by xorima** [comment]
Could you propose a better documentation for this?
