### ISSUE TITLE
Cannot configure smtp

### ISSUE THREAD

**Issue by francis826** [sous-chefs/grafana#273]
# Brief Description

Trying to configure smtp with the `grafana_config_smtp` is throwing a Chef error.

## Cookbook version

5.0.0

## Chef-client version

14.12.3

## Platform Details

Debian 10.0

## Steps to Reproduce

Code being used:

```
grafana_config_smtp 'grafana' do
  enabled true
  host '10.3.3.71:25'
  from_address 'grafana@site.com'
end
```

## Expected Result

smtp for Grafana is configured

## Actual Result

Chef error:

```
  * grafana_config_smtp[grafana] action install

    ================================================================================
    Error executing action `install` on resource 'grafana_config_smtp[grafana]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/grafana/resources/config_smtp.rb:44:in `block (3 levels) in class_from_file'
    /var/chef/cache/cookbooks/grafana/resources/config_smtp.rb:39:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/grafana/resources/config_smtp.rb:38:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/dig-grafana/recipes/smtp.rb

      1: grafana_config_smtp 'grafana' do
      2:   enabled true
      3:   host '10.3.3.71:25'
      4:   from_address 'grafana@site.com'
      5: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/dig-grafana/recipes/smtp.rb:1:in `from_file'

    grafana_config_smtp("grafana") do
      action [:install]
      default_guard_interpreter :default
      declared_type :grafana_config_smtp
      cookbook_name "dig-grafana"
      recipe_name "smtp"
      enabled true
      host "10.3.3.71:25"
      from_address "grafana@site.com"
      config_file "/etc/grafana/grafana.ini"
      instance_name "grafana"
    end

    System Info:
    ------------
    chef_version=14.12.3
    platform=debian
    platform_version=10.0
    ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
    program_name=chef-client worker: ppid=3986;start=14:52:31;
    executable=/opt/chef/bin/chef-client
```

**Stacktrace:**

Most of the stacktrace is not useful except for this:

```
>>>> Caused by Chef::Exceptions::ResourceNotFound: Cannot find a resource matching template[/etc/grafana/grafana.ini] (did you define it first?)
```

**Comment by francis826** [comment]
Now that I look closer, it looks like my `/etc/grafana/grafana.ini` is not being managed by Chef, I am wondering if that is the cause and what I'm missing to accomplish this.

**Comment by francis826** [comment]
Okay this is on me... I needed to have the following so the file is managed by Chef:

```
grafana_config 'grafana' do
end
```

**Comment by JohnRoesler** [comment]
Thank you for reporting back on the resolution :+1:
