### ISSUE TITLE
Check for dash before using

### ISSUE THREAD

**Issue by mbaitelman** [sous-chefs/grafana#351]
### :speaking_head: Foreword

It looks like the error handling isn't handling auth issues.

## :ghost: Brief Description

Checking `dash['message']` in [dashboard_api](https://github.com/sous-chefs/grafana/blob/master/libraries/dashboard_api.rb#L81) is failing with NilClass error. 
## :pancakes: Cookbook version

8.7.0
## :woman_cook:  Chef-Infra Version

14.12.9

## :tophat: Platform details

Ubuntu on AWS

## Steps To Reproduce

Not quite sure what the issue is.

## :police_car: Expected behavior

Treat as no existing dashboard.

## :heavy_plus_sign: Additional context

```        * grafana_dashboard[app-servers] action create[2020-05-18T17:01:10-07:00] INFO: Processing grafana_dashboard[app-servers] action create (corp-base::grafana line 100)
       [2020-05-18T17:01:28-07:00] ERROR: Connection refused.
       [2020-05-18T17:01:46-07:00] ERROR: Connection refused.
       [2020-05-18T17:02:04-07:00] ERROR: Connection refused.
       [2020-05-18T17:02:22-07:00] ERROR: Connection refused.
       [2020-05-18T17:02:40-07:00] ERROR: Connection refused.
       [2020-05-18T17:02:58-07:00] ERROR: Connection refused.


           ================================================================================
           Error executing action `create` on resource 'grafana_dashboard[app-servers]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `[]' for nil:NilClass

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/grafana/libraries/dashboard_api.rb:81:in `get_dashboard'
           /tmp/kitchen/cache/cookbooks/grafana/resources/dashboard.rb:65:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/corp-base/recipes/grafana.rb

           100:     grafana_dashboard dashboard do
           101:       grafana['dashboards'][dashboard].each { |property, value| send(property, value) }
           102:       action [:create, :update]
           103:     end
           104:   end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/corp-base/recipes/grafana.rb:100:in `block in from_file'

           grafana_dashboard("app-servers") do
             action [:create, :update]
             default_guard_interpreter :default
             declared_type :grafana_dashboard
             cookbook_name "corp-base"
             recipe_name "grafana"
           end

           System Info:
           ------------
           chef_version=14.12.9
           platform=ubuntu
           platform_version=18.04
           ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client

       [2020-05-18T17:02:58-07:00] INFO: Running queued delayed notifications before re-raising exception```

**Comment by xorima** [comment]
Hey,

Thanks for this and the PR, out of curiosity what is the version of grafana you are using?

**Comment by mbaitelman** [comment]
Was installing 6.3.2 but had not started the service before making the calls. 
Other resources didn't fail (data source) but this did.
