### ISSUE TITLE
Creating an org with a bad password results in a cryptic error message

### ISSUE THREAD

**Issue by tas50** [sous-chefs/grafana#80]
If you pass bad credentials in the grafana_organization LWRP you get the following cryptic error message:

```
================================================================================
Error executing action `create_if_missing` on resource 'grafana_organization[something]'
================================================================================

NameError
---------
No resource, method, or local variable named `messages' for ` ""'

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/grafana/libraries/api_helper.rb:91:in `handle_response_unauthorized'
/var/chef/cache/cookbooks/grafana/libraries/api_helper.rb:64:in `handle_response'
/var/chef/cache/cookbooks/grafana/libraries/api_helper.rb:23:in `login'
/var/chef/cache/cookbooks/grafana/libraries/organization_api.rb:57:in `get_orgs_list'
/var/chef/cache/cookbooks/grafana/providers/organization.rb:16:in `block in class_from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/cozy_grafana/recipes/default.rb
```

**Comment by JonathanTron** [comment]
Thanks for catching this one too!
