### ISSUE TITLE
undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by kemra102** [sous-chefs/grafana#81]
```
* grafana_datasource[influxdb] action create_if_missing

    ================================================================================
    Error executing action `create_if_missing` on resource 'grafana_datasource[influxdb]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `each' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/grafana/providers/datasource.rb:31:in `create'
    /var/chef/cache/cookbooks/grafana/providers/datasource.rb:16:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/azsb_graphing/recipes/default.rb

     53: grafana_datasource 'influxdb' do
     54:   source(
     55:     type: 'influxdb_09',
     56:     url: 'http://127.0.0.1:8086',
     57:     access: 'proxy',
     58:     database: 'grafana',
     59:     isdefault: true
     60:   )
     61:   action :create_if_missing
     62: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/azsb_graphing/recipes/default.rb:53:in `from_file'

    grafana_datasource("influxdb") do
      action [:create_if_missing]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :grafana_datasource
      cookbook_name "azsb_graphing"
      recipe_name "default"
      source {:type=>"influxdb_09", :url=>"http://127.0.0.1:8086", :access=>"proxy", :database=>"grafana", :isdefault=>true, :name=>"influxdb"}
      source_name "influxdb"
      host "localhost"
      port 3000
      user "admin"
      password "admin"
    end
```

The above worked in our testing on Vagrant but not when we pushed it out to Azure.

```
$ sudo chef-client --version
Chef: 12.4.1
```

Running on CentOS 6.6 with the latest version of the cookbook from the supermarket.

**Comment by kemra102** [comment]
A colleague suggested it is failing somewhere in this block: https://github.com/JonathanTron/chef-grafana/blob/master/libraries/datasource_api.rb#L101 

and due to the rescue on line 119 we get nil returned rather than the real error.

I did some snooping around on the server and it looks like the API call is failing as the Grafana Server isn't started. The logs have the following errors:

```
2015/08/27 10:23:51 [I] Database: sqlite3, ConnectionString: file:/var/lib/grafana/grafana.db?cache=shared&mode=rwc&_loc=Local
2015/08/27 10:23:51 [I] Migrator: Starting DB migration
2015/08/27 10:23:51 [I] Migrator: exec migration id: drop index UQE_user_email - v1
2015/08/27 10:23:51 [migrator.go:134 func·001()] [E] Migrator: exec FAILED migration id: drop index UQE_user_email - v1, err: no such index: UQE_user_email
2015/08/27 10:23:51 [log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: no such index: UQE_user_email
```

Not sure if the above is related to the something that the cookbook specifically is doing, but even if not the error reporting could do with some improvement if possible.

**Comment by lanyonm** [comment]
Hey @kemra102,
Thank you for reporting this. There is certainly a bug in the error handling when Grafana has failed to start which is something will will have to address.

Was the converge that failed on CentOS 6.6 in Azure the first (provisioning or bootstrapping) converge?

Thanks!

**Comment by kemra102** [comment]
Yes the above is from the first converge.

**Comment by lanyonm** [comment]
I've added more robust tests to help communicate when Grafana has not started or is not running. You should now see something like this:

```
     * grafana_datasource[graphite] action create_if_missing[2015-09-01T16:57:49+00:00] ERROR: Connection refused.
       [2015-09-01T16:57:49+00:00] ERROR: Connection refused.

       ================================================================================
       Error executing action `create_if_missing` on resource 'grafana_datasource[graphite]'
       ================================================================================

       GrafanaCookbook::ApiHelper::BackendError
       ----------------------------------------
       Connection to Grafana refused. Please ensure Grafana is running.

       Cookbook Trace:
       ---------------
       /tmp/kitchen/cache/cookbooks/grafana/libraries/api_helper.rb:108:in `handle_response_conn_refused'
       /tmp/kitchen/cache/cookbooks/grafana/libraries/api_helper.rb:68:in `handle_response'
       /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:27:in `create'
       /tmp/kitchen/cache/cookbooks/grafana/providers/datasource.rb:16:in `block in class_from_file'

       Resource Declaration:
       ---------------------
       # In /tmp/kitchen/cache/cookbooks/grafana/recipes/default.rb

       75: grafana_datasource 'graphite' do
       76:   port node['grafana']['ini']['server']['http_port']
       77:   source(
       78:     type: 'graphite',
       79:     url: 'http://graphite.example.com:8080',
       80:     access: 'proxy',
       81:     isdefault: true
       83:   action :create_if_missing
       84: end

       Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/grafana/recipes/default.rb:75:in `from_file'

       grafana_datasource("graphite") do
         action [:create_if_missing]
         retries 0
         retry_delay 2
         default_guard_interpreter :default
          declared_type :grafana_datasource
         cookbook_name "grafana"
         recipe_name "default"
         port 3000
         source_name "graphite"
         host "localhost"
         user "admin"
         password "admin"
       end
```

I don't have resources immediately available to test convergence for CentOS 6.6 in Azure, but Grafana did have an init bug in earlier versions (#61). It doesn't look like you're experiencing quite the same error, but maybe it's related? Could you confirm what version of Grafana and what version of the cookbook you're using?

**Comment by kemra102** [comment]
We are using Grafana & Cookbook versions 2.1.3.

From what I could tell something wrecked the SQLite DB on initial installation. Removing the Grafana package, the sqlite db and re-installation fixed the issue and Grafana could start normally.

**Comment by lanyonm** [comment]
We've seen a few tickets where folks have seen Grafana fail to start on the initial install. We'll keep an eye out for whether this is happen on one OS or many.
